name: word_validation
description: BLoC form validation.
version: 1.0.0+1
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ">=2.16.0"
  flutter: ">=2.10.1"

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.1

dev_dependencies:
  bloc_test: ^9.0.2
  dart_code_metrics: ^4.11.0-dev.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0


flutter:
  uses-material-design: true
