name: Tests

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2

    - name: Install app dependencies
      run: flutter pub get

    - name: Test app
      run: flutter test --coverage

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov.info
